--SELECT 'UPDATE tools SET invocation = ''' || name || ''' WHERE id = ' || id || ';' as "update invocation" FROM tools ORDER BY name;

UPDATE tools SET invocation = 'powertop' WHERE id = 43;
UPDATE tools SET invocation = 'starship' WHERE id = 13;
UPDATE tools SET invocation = 'surge' WHERE id = 40;
UPDATE tools SET invocation = 'N/A' WHERE id = 15;
UPDATE tools SET name = 'Chafa' WHERE id = 2;
UPDATE tools SET name = 'GitUI' WHERE id = 38;
UPDATE tools SET name = 'Glow' WHERE id = 28;
UPDATE tools SET name = 'Kondo' WHERE id = 47;
UPDATE tools SET name = 'Lazygit' WHERE id = 39;
UPDATE tools SET name = 'McFly' WHERE id = 45;
UPDATE tools SET name = 'ncdu', invocation = 'ncdu' WHERE id = 26;
UPDATE tools SET name = 'ncdu-zig', invocation = 'ncdu' WHERE id = 27;
UPDATE tools SET name = 'Pywal' WHERE id = 21;
UPDATE tools SET invocation = 'taproom' WHERE id = 14;
UPDATE tools SET name = 'tldr-pages' WHERE id = 29;
UPDATE tools SET name = 'tldr-python-client', invocation = 'tldr' WHERE id = 30;
UPDATE tools SET invocation = 'tlrc', invocation = 'tldr' WHERE id = 31;
UPDATE tools SET invocation = 'trash-*' WHERE id = 32;
UPDATE tools SET name = 'Wikiman' WHERE id = 34;
UPDATE tools SET name = 'Yazi' WHERE id = 16;
UPDATE tools SET name = 'Zellij' WHERE id = 17;
